theme: jekyll-theme-cayman
title: Vineet Kamat
description: I am an undergraduate student and researchers studying at Cornell University. I am pursuing a Bachellors degree in Physics, Math and Computer Science.
author: Vineet Kamat
author_email: vk284@cornell.edu